// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class MedikaLoginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void medikaLogin() {
    // Test name: Medika_Login
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    driver.get("https://medikabazaar.com/");
    // 2 | mouseOver | css=.sign |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".sign"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 3 | click | css=.login > a > span:nth-child(1) |  | 
    driver.findElement(By.cssSelector(".login > a > span:nth-child(1)")).click();
    // 4 | click | id=email |  | 
    driver.findElement(By.id("email")).click();
    // 5 | type | id=email | prasadandhale18@gmail.com | 
    driver.findElement(By.id("email")).sendKeys("prasadandhale18@gmail.com");
    // 6 | type | id=pass | Prasad@18 | 
    driver.findElement(By.id("pass")).sendKeys("Prasad@18");
    // 7 | click | css=#send2 > span |  | 
    driver.findElement(By.cssSelector("#send2 > span")).click();
    // 8 | click | css=.login > a > span:nth-child(1) |  | 
    driver.findElement(By.cssSelector(".login > a > span:nth-child(1)")).click();
    // 9 | click | css=.logo img |  | 
    driver.findElement(By.cssSelector(".logo img")).click();
    // 10 | click | css=.col-left .pt_menu:nth-child(1) > .parentMenu span |  | 
    driver.findElement(By.cssSelector(".col-left .pt_menu:nth-child(1) > .parentMenu span")).click();
    // 11 | click | css=.item:nth-child(2) .product-image |  | 
    vars.put("window_handles", driver.getWindowHandles());
    // 12 | selectWindow | handle=${win660} |  | 
    driver.findElement(By.cssSelector(".item:nth-child(2) .product-image")).click();
    // 13 | runScript | window.scrollTo(0,1) |  | 
    vars.put("win660", waitForWindow(2000));
    // 14 | runScript | window.scrollTo(0,367) |  | 
    driver.switchTo().window(vars.get("win660").toString());
    // 15 | click | id=zipcode |  | 
    js.executeScript("window.scrollTo(0,1)");
    // 16 | type | id=zipcode | 400038 | 
    js.executeScript("window.scrollTo(0,367)");
    // 17 | click | css=#zip-check > span |  | 
    driver.findElement(By.id("zipcode")).click();
    // 18 | click | id=increase |  | 
    driver.findElement(By.id("zipcode")).sendKeys("400038");
    // 19 | click | id=increase |  | 
    driver.findElement(By.cssSelector("#zip-check > span")).click();
    // 20 | click | id=increase |  | 
    driver.findElement(By.id("increase")).click();
    // 21 | click | css=#add_to_seller_cart > span > span |  | 
    driver.findElement(By.id("increase")).click();
    // 22 | runScript | window.scrollTo(0,94) |  | 
    driver.findElement(By.id("increase")).click();
    // 23 | click | id=points_all |  | 
    driver.findElement(By.cssSelector("#add_to_seller_cart > span > span")).click();
    // 24 | click | css=#reward-points-form .button:nth-child(1) > span > span |  | 
    js.executeScript("window.scrollTo(0,94)");
    // 25 | runScript | window.scrollTo(0,94) |  | 
    driver.findElement(By.id("points_all")).click();
    // 26 | click | id=coupon_code | MBBOW | 
    driver.findElement(By.cssSelector("#reward-points-form .button:nth-child(1) > span > span")).click();
    // 27 | click | css=#discount-coupon-form .button:nth-child(1) |  | 
    js.executeScript("window.scrollTo(0,94)");
    // 28 | click | css=.btn-proceed-checkout |  | 
    driver.findElement(By.id("coupon_code")).click();
    // 29 | runScript | window.scrollTo(0,82) |  | 
    driver.findElement(By.cssSelector("#discount-coupon-form .button:nth-child(1)")).click();
    // 30 | runScript | window.scrollTo(0,121) |  | 
    driver.findElement(By.cssSelector(".btn-proceed-checkout")).click();
    // 31 | runScript | window.scrollTo(0,602) |  | 
    js.executeScript("window.scrollTo(0,82)");
    // 32 | check | css=.sign |  | 
    js.executeScript("window.scrollTo(0,121)");
    // 33 | click | xpath=//span[contains(.,'Log Out')] |  | 
    js.executeScript("window.scrollTo(0,602)");
    {
      WebElement element = driver.findElement(By.cssSelector(".sign"));
      if (!element.isSelected()) {
        element.click();
      }
    }
    driver.findElement(By.xpath("//span[contains(.,\'Log Out\')]")).click();
  }
}
